### ISSUE TITLE
error running example scripts

### ISSUE THREAD

**Issue by haydenclose** [zsylvester/segmenteverygrain#11]
hi,

I have ran the example scripts both in Jupyter and in Colab and getting the same error. Have previously ran it fine so might be related to an update or package update. It does plot the figure but does not return all_grains, labels, mask_all etc...

100%|██████████| 22/22 [01:06<00:00,  3.01s/it]
100%|██████████| 21/21 [00:46<00:00,  2.20s/it]
100%|██████████| 6399/6399 [59:28<00:00,  1.79it/s]
4772it [1:21:23,  1.02s/it]
100%|██████████| 143/143 [06:31<00:00,  2.74s/it]
100%|██████████| 154/154 [00:04<00:00, 37.72it/s]
100%|██████████| 680/680 [00:48<00:00, 13.89it/s]
0.0
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-18-72a9646841c2>](https://localhost:8080/#) in <cell line: 7>()
      5 # decreasing the 'dbs_max_dist' parameter results in more SAM prompts (and longer processing times):
      6 labels, grains, coords = seg.label_grains(big_im, big_im_pred, dbs_max_dist=10.0)
----> 7 all_grains, labels, mask_all, grain_data, fig, ax = seg.sam_segmentation(sam, big_im, big_im_pred, coords, labels, min_area=50.0)

1 frames
[/usr/local/lib/python3.10/dist-packages/segmenteverygrain/segmenteverygrain.py](https://localhost:8080/#) in plot_grain_axes_and_centroids(all_grains, labels, ax, linewidth, markersize)
    763     regions = regionprops(labels.astype('int'))
    764     for ind in range(len(all_grains)-1):
--> 765         y0, x0 = regions[ind].centroid
    766         orientation = regions[ind].orientation
    767         x1 = x0 + np.cos(orientation) * 0.5 * regions[ind].minor_axis_length

IndexError: list index out of range

![image](https://github.com/zsylvester/segmenteverygrain/assets/14199264/0d58ab1a-6373-4aed-b01d-3743264e9280)

**Comment by haydenclose** [comment]
Found out the issue was the image size, seems to work when reduced.

**Comment by ZSBRO** [comment]
Hey Hayden, Just want to reach out for the step you took up to centroid masks.
