### ISSUE TITLE
Compatibility issue between seg_model.index and Keras 3

### ISSUE THREAD

**Issue by louisejuliedelhaye** [zsylvester/segmenteverygrain#12]
Hi, I have a compatibility issue when trying to use seg_model.index with Keras 3. Apparently, this version of Keras can only accept extensions such as .keras or .h5 and not .index. This is the error than I get: "Keras 3 only supports V3 .keras files and legacy H5 format files (.h5 extension). Note that the legacy SavedModel format is not supported by load_model() in Keras 3".

**Comment by zsylvester** [comment]
'segmenteverygrain' does not work with Keras 3, at least not for now. The best way to run it is to create Python environment using the [environment.yml](https://github.com/zsylvester/segmenteverygrain/blob/main/environment.yml) file. I think this will install keras 2.13.1.
