### ISSUE TITLE
Checkpoints 404 not found

### ISSUE THREAD

**Issue by Jinyiyi3** [zsylvester/segmenteverygrain#13]
Thank you for your great work. However, when I tried to run this model, the link of checkpoints showed that 404 not found, then I cannot run this code
`model.load_weights('./checkpoints/seg_model') # replace this if you have a finetuned Unet model and want to use it`
!wget "https://raw.githubusercontent.com/zsylvester/segmenteverygrain/main/segmenteverygrain/checkpoints/checkpoint"

!wget "https://raw.githubusercontent.com/zsylvester/segmenteverygrain/main/segmenteverygrain/checkpoints/seg_model.data-00000-of-00001"

!wget "https://raw.githubusercontent.com/zsylvester/segmenteverygrain/main/segmenteverygrain/checkpoints/seg_model.index"

I tried to run the latest code
`model = load_model("seg_model.keras", custom_objects={'weighted_crossentropy': seg.weighted_crossentropy})`
But it still showed error:
OSError: No file or directory found at seg_model.keras

**Comment by zsylvester** [comment]
You need to make the "seg_model.keras" file available - either place it in your current directory, or provide the path to it. The file is available [here](https://github.com/zsylvester/segmenteverygrain/tree/main/segmenteverygrain).
