### ISSUE TITLE
Colab notebook updates

### ISSUE THREAD

**Issue by ThomasMGeo** [zsylvester/segmenteverygrain#6]
Hi @zsylvester ,

Thank you! The colab notebook works great, two small changes removes the errors from it. 

`all_grains, labels, mask_all, grain_data, fig, ax = seg.sam_segmentation(sam, big_im, big_im_pred, coords, labels, min_area=50.0)`

In cell 12 (or so, might be off by 1) the outputs from the function sam_segmentation needed to be updated. 

`all_grains, labels, mask_all, fig, ax = seg.get_grains_from_patches(ax, big_im)`

Same here, around cell 17 (again, might be off by 1)

Let le know if this works for you.

Cheers,
Thomas

cc: @zanejobe

**Comment by zanejobe** [comment]
Hey ZS, excellent work! I started testing this on my MacBook M2 and couldn't get things to install correctly, I kept getting a "The Kernel crashed while executing code in the current cell or a previous cell." error when I tried to import `tensorflow` or `segmenteverygrain`. Likely an install error, just just an FYI. I will keep testing on my local machine, but Colab seems to work well for now. Processing a slab from the Guads noe!

**Comment by zsylvester** [comment]
Hi @ThomasMGeo - thanks for this, yes, I need to update both a notebooks and the module.
@zanejobe: I will try to upload soon an environment file that works on my machine (M2 Mac) and Windows machines as well. I also managed to set up an environment where tensorflow uses the GPUs of the Mac, will upload that as well. It was an effort to set it up, but totally worth it. Looking forward to seeing the results from the Guads!

**Comment by zsylvester** [comment]
@zanejobe here is the (not Mac specific) environment file: https://github.com/zsylvester/segmenteverygrain/blob/main/environment.yml
