### ISSUE TITLE
Colab is not running segmenteverygrain

### ISSUE THREAD

**Issue by LigoMan99** [zsylvester/segmenteverygrain#9]
![image](https://github.com/zsylvester/segmenteverygrain/assets/111463227/2569cb24-ece4-46e1-8caa-59e2f0fd376a)

![image](https://github.com/zsylvester/segmenteverygrain/assets/111463227/e669f9d0-ca56-4f2f-a8d9-eb0b1c5e5905)

**Comment by halqadasi** [comment]
+1, same problem here

**Comment by ThomasMGeo** [comment]
Just echo'ing others that myself and @zanejobe are having the same issue.

**Comment by zanejobe** [comment]
agreed - maybe a pypi issue? I also have the same issue on my local installation (using your env file) - using `conda list` it shows 0.13.0 installed but I can't import it into the notebook using that env

**Comment by zsylvester** [comment]
Thanks y'all for the heads up! It's weird because I think it worked when I tested it.
I am working on it (and starting to think it was a bad idea to switch from 'setup.py' to 'pyproject.toml').

**Comment by zsylvester** [comment]
It works for me now in Google Colab - 'pip install segmenteverygrain' should install the latest version, which is v0.1.7. Something was off in the way I set up 'pyproject.toml' (the main .py file was not actually included in the distribution), but it seems to be working now, after switching back to 'setup.py'. Let me know if you still run into issues. cc @zanejobe @ThomasMGeo

**Comment by zanejobe** [comment]
Nice! Thanks man, it's working in colab now for me too. Still messing with the local installation, which is likely a tensorflow issue, not related to segmenteverygrain. Thanks for getting to this so fast!
